### ISSUE TITLE
500 Error after latest merge

### ISSUE THREAD

**Issue by bentwnghk** [okisdev/ChatChat#144]
The docker log shows the following:

Error: Cannot find module 'webpack'
Require stack:
- /app/node_modules/workbox-webpack-plugin/build/generate-sw.js
- /app/node_modules/workbox-webpack-plugin/build/index.js
- /app/node_modules/next-pwa/index.js
- /app/next.config.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
    at /app/node_modules/next/dist/server/require-hook.js:185:36
    at Module._load (node:internal/modules/cjs/loader:922:27)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/app/node_modules/workbox-webpack-plugin/build/generate-sw.js:18:35)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/app/node_modules/workbox-webpack-plugin/build/generate-sw.js',
    '/app/node_modules/workbox-webpack-plugin/build/index.js',
    '/app/node_modules/next-pwa/index.js',
    '/app/next.config.js'
  ]
}

Is there a fix for the error?

**Comment by okisdev** [comment]
Hi there, Thanks for reporting this.

Be fixed now.
