### ISSUE TITLE
New user signup fails

### ISSUE THREAD

**Issue by bentwnghk** [okisdev/ChatChat#27]
On the ../register page, after entering an email address, clicking on the signup button produces no effect, and no email is sent.

Below is my database log:
```
2023-05-04 23:21:16.764 HKT [3383] ERROR:  relation "public.users" does not exist at character 344
2023-05-04 23:21:16.764 HKT [3383] STATEMENT:  SELECT "public"."users"."id", "public"."users"."platform", "public"."users"."name", "public"."users"."email", "public"."users"."emailVerified", "public"."users"."image", "public"."users"."created_at", "public"."users"."updated_at", "public"."users"."defaultProvider", "public"."users"."openAIKey", "public"."users"."allowRecordCloudSync" FROM "public"."users" WHERE ("public"."users"."email" = $1 AND 1=1) LIMIT $2 OFFSET $3
```
Below is my docker log:
```
[next-auth][error][adapter_error_getUserByEmail] 
https://next-auth.js.org/errors#adapter_error_getuserbyemail 
Invalid `prisma.user.findUnique()` invocation:
The table `public.users` does not exist in the current database. {
  message: '\n' +
    'Invalid `prisma.user.findUnique()` invocation:\n' +
    '\n' +
    '\n' +
    'The table `public.users` does not exist in the current database.',
  stack: 'Error: \n' +
    'Invalid `prisma.user.findUnique()` invocation:\n' +
    '\n' +
    '\n' +
    'The table `public.users` does not exist in the current database.\n' +
    '    at pn.handleRequestError (/app/node_modules/@prisma/client/runtime/library.js:176:6477)\n' +
    '    at pn.handleAndLogRequestError (/app/node_modules/@prisma/client/runtime/library.js:176:5907)\n' +
    '    at pn.request (/app/node_modules/@prisma/client/runtime/library.js:176:5786)\n' +
    '    at async t._request (/app/node_modules/@prisma/client/runtime/library.js:179:10484)',
  name: 'Error'
}
Error: 
Invalid `prisma.user.findUnique()` invocation:
The table `public.users` does not exist in the current database.
    at pn.handleRequestError (/app/node_modules/@prisma/client/runtime/library.js:176:6477)
    at pn.handleAndLogRequestError (/app/node_modules/@prisma/client/runtime/library.js:176:5907)
    at pn.request (/app/node_modules/@prisma/client/runtime/library.js:176:5786)
    at async t._request (/app/node_modules/@prisma/client/runtime/library.js:179:10484) {
  name: 'GetUserByEmailError',
  code: 'P2021'
```

**Comment by okisdev** [comment]
Hi. Have you set up all the environment variables?

**Comment by bentwnghk** [comment]
Below is my docker compose file:
```
version: '3'
services:
  web:
    container_name: chatchat
    image: bentwng/chatchat:latest
    environment:
      NODE_ENV: production
      BASE_URL: https://xxx.net
      DATABASE_URL: postgresql://postgres:thisisapassword@chatchat-db:5432/chatchat
      NEXTAUTH_URL: xxx.net
      NEXTAUTH_SECRET: xxxxxxxxxxxxxxxx
      EMAIL_HOST: smtp.gmail.com
      EMAIL_PORT: 587
      EMAIL_USERNAME: xxx@gmail.com
      EMAIL_PASSWORD: xxxxxxxxxxxxxxx
      EMAIL_FROM: xxx@gmail.com
      # GITHUB_CLIENT_ID:
      # GITHUB_CLIENT_SECRET:
      # GOOGLE_CLIENT_ID:
      # GOOGLE_CLIENT_SECRET:
      OPENAI_API_KEY:
      # OPENAI_API_ENDPOINT:
      TZ: Asia/Hong_Kong
    ports:
      - "3009:3000"
    restart: always
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:14
    restart: always
    hostname: chatchat-db
    user: postgres
    environment:
      TZ: Asia/Hong_Kong
      PGTZ: Asia/Hong_Kong
      POSTGRES_DB: chatchat
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: thisisapassword
    expose:
      - 6799
    ports:
      - "6799:5432"
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-q",
          "-d",
          "postgres",
          "-U",
          "postgres"
        ]
      interval: 5s
      timeout: 5s
      retries: 5
```

**Comment by okisdev** [comment]
Please run `npx prisma db pull` to reflect models on your database

**Comment by okisdev** [comment]
Sorry. My Bad. It is `npx prisma db push`. Try again now. If the tables are shown in the database, will be good to go.

**Comment by okisdev** [comment]
No worries. Thanks for your support. The issue will be closed now.
