### ISSUE TITLE
Error [TypeError]: Failed to parse URL from https://()=>process.env.BASE_URL/api/team/info?accessCode

### ISSUE THREAD

**Issue by mwnu** [okisdev/ChatChat#58]
我创建了团队，然后应用设置服务提供商为Team，填入Team Access Code（访问码），然后对话出错，日志如下：

```
Error [TypeError]: Failed to parse URL from https://()=>process.env.BASE_URL/api/team/info?accessCode=******
    at context.fetch (file:///app/node_modules/next/dist/server/web/sandbox/context.js:265:38)
    at H (file:///app/.next/server/app/api/messages/route.js:22:38145)
    at <unknown> (file:///app/.next/server/app/api/messages/route.js:22:40095)
    at <unknown> (file:///app/.next/server/app/api/messages/route.js:22:45261)
    at a.with (file:///app/.next/server/app/api/messages/route.js:5:18870)
    at l.with (file:///app/.next/server/app/api/messages/route.js:5:13050)
    at l.startActiveSpan (file:///app/.next/server/app/api/messages/route.js:5:28070)
    at i.startActiveSpan (file:///app/.next/server/app/api/messages/route.js:5:28732)
    at <unknown> (file:///app/.next/server/app/api/messages/route.js:22:45113)
    at a.with (file:///app/.next/server/app/api/messages/route.js:5:18870)
```

我尝试BASE_URL去掉前缀（https://），NODE ENV环境变量改为：development，没有解决问题。

**Comment by okisdev** [comment]
请问是在本地部署的吗？

**Comment by mwnu** [comment]
> 请问是在本地部署的吗？

是在家庭服务器上部署的。

**Comment by okisdev** [comment]
如果是家庭服务器的话，暂时建议是使用设置全局变量 `OPENAI_API_KEY` 和 `OPENAI_API_ENDPOINT`

因为在内网环境下没办法使用 `/api/team/info?accessCode=xxx`

**Comment by mwnu** [comment]
> 如果是家庭服务器的话，暂时建议是使用设置全局变量 `OPENAI_API_KEY` 和 `OPENAI_API_ENDPOINT`
> 
> 因为在内网环境下没办法使用 `/api/team/info?accessCode=xxx`

进行了端口映射，外网可以访问的，就是团队用不了，目前设的就是全局变量 OPENAI_API_KEY 和 OPENAI_API_ENDPOINT

**Comment by okisdev** [comment]
尝试一下最新的代码，移除了`BASE_URL`，改用`NEXTAUTH_URL`替代

**Comment by mwnu** [comment]
> 尝试一下最新的代码，移除了`BASE_URL`，改用`NEXTAUTH_URL`替代

问题解决，太棒了，期待更多团队功能！
